<?php

namespace Database\Seeders\Admin;

use App\Models\Admin\SmsTemplate;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SmsTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sms_templates = array(
            array('act' => 'PASS_RESET_CODE','name' => 'Password Reset','subj' => 'Password Reset','sms_body' => 'Your account recovery code is: {{code}}','shortcodes' => ' {"code":"Password Reset Code","ip":"IP of User","browser":"Browser of User","operating_system":"Operating System of User","time":"Request Time"}','sms_status' => '1','created_at' => '2019-09-25 05:04:05','updated_at' => '2021-01-06 06:49:06'),
            array('act' => 'PASS_RESET_DONE','name' => 'Password Reset Confirmation','subj' => 'You have Reset your password','sms_body' => 'Your password has been changed successfully','shortcodes' => '{"ip":"IP of User","browser":"Browser of User","operating_system":"Operating System of User","time":"Request Time"}','sms_status' => '1','created_at' => '2019-09-25 05:04:05','updated_at' => '2020-03-07 16:23:47'),
            array('act' => 'EVER_CODE','name' => 'Email Verification','subj' => 'Please verify your email address','sms_body' => 'Your email verification code is: {{code}}','shortcodes' => '{"code":"Verification code"}','sms_status' => '1','created_at' => '2019-09-25 05:04:05','updated_at' => '2021-01-04 05:35:10'),
            array('act' => 'SVER_CODE','name' => 'SMS Verification ','subj' => 'Please verify your phone','sms_body' => 'Your phone verification code is: {{code}}','shortcodes' => '{"code":"Verification code"}','sms_status' => '1','created_at' => '2019-09-25 05:04:05','updated_at' => '2020-03-08 07:28:52'),
            array('act' => 'ADD_MONEY_COMPLETE','name' => 'Automated Add Money- Successful','subj' => 'Add money Completed Successfully','sms_body' => '{{amount}} {{currency}} Add Money successfully by {{gateway_name}}','shortcodes' => '{"trx":"Transaction Number","amount":"Request Amount By user","charge":"Gateway Charge","currency":"Site Currency","rate":"Conversion Rate","method_name":"Add Money Method Name","method_currency":"Add Money Method Currency","method_amount":"Add Money Method Amount After Conversion"}','sms_status' => '1','created_at' => '2020-06-25 00:00:00','updated_at' => '2021-07-01 12:09:23'),
            array('act' => 'ADD_MONEY_REQUEST','name' => 'Manual Add Money- User Requested','subj' => 'Add money Request Submitted Successfully','sms_body' => '{{amount}} Add Money requested by {{method}}. Charge: {{charge}} . Trx: {{trx}}
                                ','shortcodes' => '{"trx":"Transaction Number","amount":"Request Amount By user","charge":"Gateway Charge","currency":"Site Currency","rate":"Conversion Rate","method_name":"Deposit Method Name","method_currency":"Add Money Method Currency","method_amount":"Add Money Method Amount After Conversion"}','sms_status' => '1','created_at' => '2020-06-01 00:00:00','updated_at' => '2021-07-01 12:10:02'),
            array('act' => 'ADD_MONEY_APPROVE','name' => 'Manual Add Money - Admin Approved','subj' => 'Your Add Money is Approved','sms_body' => 'Admin Approve Your {{amount}} add money request by {{gateway_name}} TrxId: {{trx}}','shortcodes' => '{"trx":"Transaction Number","amount":"Request Amount By user","charge":"Gateway Charge","currency":"Site Currency","rate":"Conversion Rate","method_name":"Deposit Method Name","method_currency":"Deposit Method Currency","method_amount":"Deposit Method Amount After Conversion", "post_balance":"Users Balance After this operation"}','sms_status' => '1','created_at' => '2020-06-17 00:00:00','updated_at' => '2020-06-15 00:00:00'),
            array('act' => 'ADD_MONEY_REJECT','name' => 'Manual Add Money- Admin Rejected','subj' => 'Your Add Money Request is Rejected','sms_body' => 'Admin Rejected Your {{amount}} add money request by {{gateway_name}},Rejection Reason: {{rejection_message}},TrxId: {{trx}}','shortcodes' => '{"trx":"Transaction Number","amount":"Request Amount By user","charge":"Gateway Charge","currency":"Site Currency","rate":"Conversion Rate","method_name":"Deposit Method Name","method_currency":"Deposit Method Currency","method_amount":"Deposit Method Amount After Conversion","rejection_message":"Rejection message"}','sms_status' => '1','created_at' => '2020-06-10 00:00:00','updated_at' => '2020-06-15 00:00:00'),
            array('act' => 'WITHDRAW_REQUEST','name' => 'Withdraw  - User Requested','subj' => 'Withdraw Request Submitted Successfully','sms_body' => 'Withdraw Money: {{amount}} withdraw requested by {{method_name}}, Method Currency {{currency}}. You will get {{will_get}}. Trx: {{trx}}','shortcodes' => '{"trx":"Transaction Number","amount":"Request Amount By user","charge":"Gateway Charge","currency":"Site Currency","rate":"Conversion Rate","method_name":"Deposit Method Name","method_currency":"Deposit Method Currency","method_amount":"Deposit Method Amount After Conversion", "post_balance":"Users Balance After this operation", "delay":"Delay time for processing"}','sms_status' => '1','created_at' => '2020-06-08 00:00:00','updated_at' => '2021-05-08 12:49:06'),
            array('act' => 'WITHDRAW_REJECT','name' => 'Withdraw - Admin Rejected','subj' => 'Withdraw Request has been Rejected and your money is refunded to your account','sms_body' => 'Admin Rejected Your {{amount}} withdraw request by {{method}}. Transaction {{trx}},Rjection Reason: {{reject_reason}}, Rejected At: {{time}}.','shortcodes' => '{"trx":"Transaction Number","amount":"Request Amount By user","charge":"Gateway Charge","method_name":"Deposit Method Name","method_currency":"Deposit Method Currency","method_amount":"Deposit Method Amount After Conversion", "post_balance":"Users Balance After this operation", "admin_details":"Details Provided By Admin"}','sms_status' => '1','created_at' => '2020-06-10 00:00:00','updated_at' => '2021-07-01 11:02:47'),
            array('act' => 'WITHDRAW_APPROVE','name' => 'Withdraw - Admin  Approved','subj' => 'Withdraw Request has been Processed and your money is sent','sms_body' => 'Admin Approve Your {{amount}} withdraw request by {{method}}. Transaction {{trx}}, Approved At: {{time}}.','shortcodes' => '{"trx":"Transaction Number","amount":"Request Amount By user","charge":"Gateway Charge","method_name":"Deposit Method Name","method_currency":"Deposit Method Currency","method_amount":"Deposit Method Amount After Conversion", "admin_details":"Details Provided By Admin"}','sms_status' => '1','created_at' => '2020-06-11 00:00:00','updated_at' => '2021-07-01 11:10:13'),
            array('act' => 'BAL_ADD','name' => 'Balance Add by Admin','subj' => 'Your Account has been Credited','sms_body' => '{{amount}} {{currency}} credited in your account. Your Current Balance {{remaining_balance}} {{currency}} . Transaction: #{{trx}}','shortcodes' => '{"trx":"Transaction Number","amount":"Request Amount By Admin","currency":"Site Currency", "post_balance":"Users Balance After this operation"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-01-06 06:46:18'),
            array('act' => 'BAL_SUB','name' => 'Balance Subtracted by Admin','subj' => 'Your Account has been Debited','sms_body' => '{{amount}} {{currency}} debited from your account. Your Current Balance {{remaining_balance}} {{currency}} . Transaction: #{{trx}}','shortcodes' => '{"trx":"Transaction Number","amount":"Request Amount By Admin","currency":"Site Currency", "post_balance":"Users Balance After this operation"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2019-11-10 15:07:12'),
            array('act' => 'MONEY_OUT','name' => 'Money Out','subj' => 'Money Out','sms_body' => 'Cash Out  {{amount}} {{curr_code}} to {{agent}} successful.
                              Charge {{charge}} {{curr_code}}. Remaining Balance {{balance}} {{curr_code}}. TrxID {{trx}} at {{time}}.','shortcodes' => '{"amount":"Cash out amount","curr_code":"currency code", "agent":"Agent user name or mail","charge":"Cash out charge","trx":"transaction id","time":"cash out time and date","balance":"Remaining Balance"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-08-17 18:57:07'),
            array('act' => 'MONEY_OUT_TO_AGENT','name' => 'Money Out To Agent','subj' => 'Money Out','sms_body' => '<div>Cash Out  <b>{{amount}} {{curr_code}}</b> from <b>{{user}}</b> successful. <br></div><div>Your New Balance <b>{{balance}} {{curr_code}}</b>. </div><div>TrxID <b>{{trx}}</b> at <b>{{time}}</b>.</div>','shortcodes' => '{"amount":"Cash out amount","curr_code":"currency code", "user":"User name or email","trx":"transaction id","time":"cash out time and date","balance":"Remaining Balance"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-08-17 18:57:35'),
            array('act' => 'MAKE_PAYMENT','name' => 'Make Payment','subj' => 'Make Payment','sms_body' => 'Make Payment To: {{to_user}}, Amount: {{amount}}  successful.
                    Charge {{charge}},Remaining Balance {{balance}}.
                    TrxID {{trx}} at {{time}}.','shortcodes' => '{"amount":"Payment amount","curr_code":"currency code", "marchant":"Marchant user name or mail","charge":"Payment charge","trx":"transaction id","time":"payment time and date","balance":"Remaining Balance"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-08-19 14:12:00'),
            array('act' => 'MAKE_PAYMENT_MERCHANT','name' => 'Make Payment marchant','subj' => 'Make Payment','sms_body' => 'Make Payment From: {{from_user}}, Amount: {{amount}} successful.Remaining Balance {{balance}}.TrxID {{trx}} at {{time}}.','shortcodes' => '{"amount":"Payment amount","curr_code":"currency code", "user":"User username or mail","charge":"Payment charge","trx":"transaction id","time":"payment time and date","balance":"Remaining Balance"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-06-30 14:15:11'),
            array('act' => 'EXCHANGE_MONEY','name' => 'Exchange Money','subj' => 'Exchange Money','sms_body' => 'Exchanged {{from_wallet_amount}} {{from_wallet_curr}} from wallet ( {{from_wallet_curr}} ) To wallet ( {{to_wallet_curr}} ) successful.
                              Exchanged amount : {{to_wallet_amount}} {{to_wallet_curr}}.

                              Remaining balance of  ( {{from_wallet_curr}} ) is : {{from_balance}} {{from_wallet_curr}}
                              New balance of  ( {{to_wallet_curr}} ) is : {{to_balance}}  {{to_wallet_curr}}

                              TrxID : {{trx}}
                              Time :  {{time}}','shortcodes' => '{"from_wallet_amount":"Amount from wallet","from_wallet_curr":"From wallet currency","to_wallet_amount":"Amount to wallet","to_wallet_curr":"To wallet currency","from_balance":"From wallet remaining balance","to_balance":"To wallet new balance","trx":"Transaction id","time":"Exchange Time"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-06-30 15:08:43'),
            array('act' => 'SEND_MONEY','name' => 'Send Money','subj' => 'Send Money','sms_body' => 'Send Money {{amount}} to {{to_user}} successful.
                    Charge {{charge}},Remaining Balance {{balance}}.
                    TrxID {{trx}} at {{time}}.','shortcodes' => '{"amount":"Transfer amount","curr_code":"currency code", "to_user":"user name or mail of receiver","charge":"Transfer charge","trx":"transaction id","time":"Transfer time and date","balance":"Remaining Balance"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-06-30 15:09:44'),
            array('act' => 'RECEIVED_MONEY','name' => 'Received Money','subj' => 'Received Money','sms_body' => 'Received Money {{amount}} from {{from_user}} successful.Remaining Balance {{balance}}.TrxID {{trx}} at {{time}}.','shortcodes' => '{"amount":"Receive amount","curr_code":"currency code", "from_user":"user name or mail of sender","trx":"transaction id","time":"Received time and date","balance":"New Balance"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-06-30 15:15:55'),
            array('act' => 'REQUEST_MONEY','name' => 'Request Money','subj' => 'Request Money','sms_body' => 'Money Request {{amount}} {{curr_code}} from {{requestor}}  at {{time}}.','shortcodes' => '{"amount":"Receive amount","curr_code":"currency code", "requestor":"user name or mail of requestor","time":"Request time and date","note":"Note from requestor"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-06-30 16:17:24'),
            array('act' => 'ACCEPT_REQUEST_MONEY_REQUESTOR','name' => 'Accept request money mail to requestor','subj' => 'Accept Request Money','sms_body' => 'Money Request {{amount}} {{curr_code}} from {{requestor}}  at {{time}}.','shortcodes' => '{"amount":"Request amount","curr_code":"currency code", "to_requested":"Requeted to whom","time":"Request time and date","balance":"New Balance","trx":"Transaction id","charge":"money request charge"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-06-30 17:03:02'),
            array('act' => 'ACCEPT_REQUEST_MONEY','name' => 'Accept request money','subj' => 'Accept Request Money','sms_body' => 'Your\'ve Accepted Money Request {{amount}} {{curr_code}} from  {{requestor}}  at {{time}}.
                              Your new balance is : {{balance}} {{curr_code}}
                              TrxID : {{trx}}','shortcodes' => '{"amount":"Request amount","curr_code":"currency code", "requestor":"Requestor","time":"Accept time and date","balance":"New Balance","trx":"Transaction id"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-06-30 16:50:39'),
            array('act' => 'MONEY_IN','name' => 'Money In','subj' => 'Money In','sms_body' => 'Cash In  {{amount}} {{curr_code}} from {{agent}} successful.
                              Your New Balance {{balance}} {{curr_code}}. TrxID {{trx}} at {{time}}.','shortcodes' => '{"amount":"Cash in amount","curr_code":"currency code", "agent":"Agent user name or mail","trx":"transaction id","time":"cash in time and date","balance":"New Balance"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-08-10 17:53:02'),
            array('act' => 'MONEY_IN_AGENT','name' => 'Money In Agent','subj' => 'Money In','sms_body' => '<div>Cash in <b>{{amount}} {{curr_code}}</b> to <b>{{user}}</b> successful. <br></div><div>Your Remaining Balance <b>{{balance}} {{curr_code}}</b>. </div><div>TrxID <b>{{trx}}</b> at <b>{{time}}</b>.</div>','shortcodes' => '{"amount":"Cash in amount","curr_code":"currency code", "user":"User name or email","trx":"transaction id","time":"cash in time and date","balance":"Remaining Balance","charge":"cash in charge"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-08-10 17:53:14'),
            array('act' => 'MONEY_IN_COMMISSION_AGENT','name' => 'Money In Commission of Agent','subj' => 'Cash In Commission','sms_body' => '<div>Commission of <b>{{amount}} {{curr_code}}</b> cash in received successfully. <br></div><div>Your New Balance <b>{{balance}} {{curr_code}}</b>. </div><div>TrxID <b>{{trx}}</b> at <b>{{time}}</b>.</div>','shortcodes' => '{"amount":"Cash in amount","curr_code":"currency code", "trx":"transaction id","time":"cash in time and date","balance":"New Balance","commission":"Cash in commission to agent"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-07-01 14:34:27'),
            array('act' => 'BILL_PAY','name' => 'Bill Pay Request','subj' => 'Bill Pay Request Send Successful','sms_body' => 'Bill Pay: {{amount}}, Bill Type: {{bill_type}}, Bill Number: {{bill_number}} successful. Remaining Balance {{balance}}.TrxID {{trx}} at {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-05 14:16:57','updated_at' => '2023-07-05 14:16:57'),
            array('act' => 'MOBILE_TOPUP','name' => 'Mobile Top Up Request','subj' => 'Mobile Top Up Request Sent Successfully','sms_body' => 'Mobile TopUp: {{amount}}, TopUp Type: {{topup_type}}, Mobile Number: {{mobile_number}} successful. Remaining Balance {{balance}}.TrxID {{trx}} at {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-05 14:21:50','updated_at' => '2023-07-05 14:21:50'),
            array('act' => 'VIRTUAL_CARD_BUY','name' => 'Virtual Card Buy','subj' => 'Virtual Card Buy Successfully','sms_body' => 'Virtual Card Buy Successfully:-
                    Request Amount{{request_amount}}, Card Amount: {{card_amount}}, Card Pan: {{card_pan}} successful. Remaining Balance {{balance}}.TrxID {{trx}} at {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-05 14:44:10','updated_at' => '2023-07-05 14:44:10'),
            array('act' => 'VIRTUAL_CARD_FUND','name' => 'Virtual Card Fund','subj' => 'Virtual Card Fund Successfully','sms_body' => 'Virtual Card Fund Successfully:-
                    Fund Amount{{request_amount}}, Card Amount: {{card_amount}}, Card Pan: {{card_pan}} successful. Remaining Balance {{balance}}.TrxID {{trx}} at {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-05 14:48:25','updated_at' => '2023-07-05 14:48:25'),
            array('act' => 'SEND_REMITTANCE','name' => 'Send Remittance','subj' => 'Send Remittance Successfully','sms_body' => 'Send Remittance: From Country: {{form_country}}, To Country: {{to_country}}, Transaction Type: {{transaction_type}}, Recipient: {{recipient}}, Send Amount: {{send_amount}},Recipient Get: {{receipient_amount}}  successful. Remaining Balance {{balance}}.TrxID {{trx}} at {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-05 16:24:11','updated_at' => '2023-07-05 16:24:11'),
            array('act' => 'KYC_APPROVED','name' => 'KYC Approved','subj' => 'KYC Approved Successfully','sms_body' => 'Your KYC verification request is approved by admin. Approved At {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-05 17:00:28','updated_at' => '2023-07-05 17:00:28'),
            array('act' => 'KYC_REJECTED','name' => 'KYC Rejected','subj' => 'KYC Rejected Successfully','sms_body' => 'Your KYC verification request is rejected by admin. Rejection Reason {{reason}}, Rejected At {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-05 17:02:39','updated_at' => '2023-07-05 17:02:39'),
            array('act' => 'BILL_PAY_APPROVED','name' => 'Bill Pay Approved','subj' => 'Bill Pay Approved Successfully','sms_body' => 'Bill Pay Approved Successfully
                      Amount: {{amount}}, Bill Type: {{bill_type}}, Bill Number: {{bill_number}},TrxID: {{trx}} at {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-06 09:53:15','updated_at' => '2023-07-06 09:53:15'),
            array('act' => 'BILL_PAY_REJECTED','name' => 'Bill Pay Rejected','subj' => 'Bill Pay Rejected Successfully','sms_body' => 'Bill Pay Rejected
                      Amount: {{amount}}, Bill Type: {{bill_type}}, Bill Number: {{bill_number}}. Remaining Balance {{balance}}.TrxID: {{trx}}, Rejected Reason: {{reason}}, at {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-06 09:55:22','updated_at' => '2023-07-06 09:55:22'),
            array('act' => 'MOBILE_TOPUP_APPROVED','name' => 'Mobile TopUp Approved','subj' => 'Mobile TopUp Approved Successfully','sms_body' => 'Mobile TopUp Approved  Amount:  {{amount}}, TopUp Type: {{topup_type}}, Mobile Number: {{mobile_number}}.TrxID {{trx}} at {{time}}.
                      ','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-06 10:36:52','updated_at' => '2023-07-06 10:36:52'),
            array('act' => 'MOBILE_TOPUP_REJECTED','name' => 'Mobile TopUp Rejected','subj' => 'Mobile TopUp Rejected Successfully','sms_body' => 'Mobile TopUp Rejected  Amount:  {{amount}}, TopUp Type: {{topup_type}}, Mobile Number: {{mobile_number}}, Remaining Balance: {{balance}}.TrxID {{trx}}, Rejected Reason:{{reason}} at {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-06 10:38:05','updated_at' => '2023-07-06 10:38:05'),
            array('act' => 'REMITTANCE_APPROVED','name' => 'Send Remittance Approved','subj' => 'Send Remittance Approved Successfully','sms_body' => 'Send Remittance Approved  From Country: {{form_country}}, To Country: {{to_country}}, Transaction Type: {{transaction_type}}, Recipient: {{recipient}}, Send Amount: {{send_amount}},Recipient Get: {{receipient_amount}} , TrxID {{trx}} at {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-06 10:52:18','updated_at' => '2023-07-06 10:52:18'),
            array('act' => 'REMITTANCE_REJECTED','name' => 'Send Remittance Rejected','subj' => 'Send Remittance Rejected Successfully','sms_body' => 'Send Remittance Rejected  From Country: {{form_country}}, To Country: {{to_country}}, Transaction Type: {{transaction_type}}, Recipient: {{recipient}}, Send Amount: {{send_amount}},Recipient Get: {{receipient_amount}}, Remaining Balance {{balance}}.TrxID: {{trx}},  Rejected  Reason: {{reason}} at {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-06 10:52:18','updated_at' => '2023-07-06 10:52:18'),
            array('act' => 'SEND_REMITTANCE_AGENT','name' => 'Send Remittance','subj' => 'Send Remittance Successfully','sms_body' => 'Send Remittance: From Country: {{form_country}}, To Country: {{to_country}}, Transaction Type: {{transaction_type}}, Sender Recipient: {{recipient}},Receiver Recipient: {{receiver_recipient}}, Send Amount: {{send_amount}},Receipient Get: {{receipient_amount}}  successful. Remaining Balance {{balance}}.TrxID {{trx}} at {{time}}.','shortcodes' => '{"trx":"Transaction",charge":"Charge","currency":"Site Currency"}','sms_status' => '1','created_at' => '2023-07-31 12:20:19','updated_at' => '2023-07-31 12:20:19'),
            array('act' => 'MONEY_OUT','name' => 'Money Out','subj' => 'Money Out','sms_body' => 'Money Out To: {{to_user}}, Amount: {{amount}}  successful.Charge {{charge}},Remaining Balance {{balance}}.TrxID {{trx}} at {{time}}.','shortcodes' => '{"amount":"Money Out Amount","curr_code":"currency code", "Agent":"Agent user name or mail","charge":"Payment charge","trx":"transaction id","time":"payment time and date","balance":"Remaining Balance"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-08-19 14:12:00'),
            array('act' => 'MONEY_OUT_AGENT','name' => 'Money Out Agent','subj' => 'Money Out Agent','sms_body' => 'Money Out From: {{from_user}}, Amount: {{amount}} successful.Remaining Balance {{balance}}.TrxID {{trx}} at {{time}}.','shortcodes' => '{"amount":"Payment amount","curr_code":"currency code", "agent":"User username or mail","charge":"Payment charge","trx":"transaction id","time":"payment time and date","balance":"Remaining Balance"}','sms_status' => '1','created_at' => '2019-09-15 01:14:22','updated_at' => '2021-06-30 14:15:11'),
          );
        SmsTemplate::truncate();
        SmsTemplate::insert($sms_templates);
    }
}
